apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: peva0411/sns-payment:latest
        livenessProbe:
          httpGet:
            path: api/health/liveness
            port: 3000
        readinessProbe:
          httpGet:
            path: api/health/readiness
            port: 3000
        resources: 
          requests:
            cpu: 500m 
            memory: 10Mi
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: CONFIG_DIR
            value: "/opt/sns/app/config"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-config
                key: redis_password
        imagePullPolicy: "IfNotPresent"
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: payment
