apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        livenessProbe:
          tcpSocket:
            port: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
        resources: 
          requests:
            cpu: 250m 
            memory: 256Mi
        image: redis:6.0.4-alpine
        volumeMounts:
        - name: conf
          mountPath: "/usr/local/etc/redis"
        ports:
        - containerPort: 6379
      volumes:
      - name: conf
        secret:
          secretName: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sns
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
